Added .hushlogin to be placed in user's home

diff --git a/_misc/git-shell-commands/add-key b/_misc/git-shell-commands/add-key
--- a/_misc/git-shell-commands/add-key
+++ b/_misc/git-shell-commands/add-key
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 if [ $# -lt 2 ] || [ `wc -c <<< $@` -lt 380 ] || ! grep -iq '[rd]sa' <<< $1 || ! grep -q '^[A-Za-z0-9+/]\+=*$' <<< $2; then
-	echo "Error: not a valid key. Expected format: 'ssh-dsa <ssh key>'" 1>&2
+	echo "Error: not a valid key. Expected format: 'ssh-rsa <ssh key> [user@host]'" 1>&2
 	echo "$@" 1>&2
 	exit 1
 fi
diff --git a/_misc/git-shell-commands/init b/_misc/git-shell-commands/init
--- a/_misc/git-shell-commands/init
+++ b/_misc/git-shell-commands/init
@@ -7,8 +7,8 @@ fi
 REPO_NAME="$1"
 grep -q '\.git$' <<< $REPO_NAME || REPO_NAME="${REPO_NAME}.git"
 if [ -d "$REPO_NAME" ] && [ -n "`ls -1 $REPO_NAME`" ]; then
-    echo "Error: repository '$REPO_NAME' already exists" 1>&2
-    exit 2
+	echo "Error: repository '$REPO_NAME' already exists" 1>&2
+	exit 2
 fi
 mkdir -vp "$REPO_NAME" && cd "$REPO_NAME" && git init --bare
 logger -t git.init -p daemon.notice "Created repo $@ ($?)"
