Added logging to git-shell-commands

diff --git a/_misc/git-shell-commands/init b/_misc/git-shell-commands/init
--- a/_misc/git-shell-commands/init
+++ b/_misc/git-shell-commands/init
@@ -6,5 +6,9 @@ if [ $# -lt 1 ] || grep -q '\.\./\|[[:space:]:]/\|[[:space:]:]\.ssh\|git-shell-c
 fi
 REPO_NAME="$1"
 grep -q '\.git$' <<< $REPO_NAME || REPO_NAME="${REPO_NAME}.git"
-[ -d "$REPO_NAME" ] && [ -n "`ls -1 $REPO_NAME`" ] && echo "Error: repository '$REPO_NAME' already exists" 1>&2 && exit 2
-mkdir -vp "$REPO_NAME" 1>&2 && cd "$REPO_NAME" && git init --bare 1>&2
+if [ -d "$REPO_NAME" ] && [ -n "`ls -1 $REPO_NAME`" ]; then
+    echo "Error: repository '$REPO_NAME' already exists" 1>&2
+    exit 2
+fi
+mkdir -vp "$REPO_NAME" && cd "$REPO_NAME" && git init --bare
+logger -t git.init -p daemon.notice "Created repo $@ ($?)"
